### ISSUE TITLE
9th frame bug

### ISSUE THREAD

**Issue by Sim-fo** [clpachec/BowlingTest#1]
There is an error in the calculation of bowling scores. If in the 9th frame the player does not knock down any pins with the second throw, then in the 10th frame the third bonus throw is not offered.
![BowlingTestBug](https://github.com/clpachec/BowlingTest/assets/8295555/9d7f9f0b-122d-48ed-8ac8-b62636e4e9ec)

**Comment by clpachec** [comment]
Thanks for the comment, This project is for a coding interview but I committed a fix. The problem was due to the scores being input as numbers instead of a spare symbol (`/`). I've updated the code to convert the score to a spare if the two throws add up to 10
